name: test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout service repository"
      uses: actions/checkout@v3
      with:
        path: main

    - name: "Checkout central-helm-chart repository"
      uses: actions/checkout@v3
      with:
        repository: mehmetca-tr/central-helm-chart
        path: central-helm-chart
    
    - name: Copy from central helm templates to service level charts folder
      run: cp -rp central-helm-chart/templates ./main/charts
      shell: bash

    - name: "Create IMAGE_NAME environment variable"
      run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      shell: bash

    - name: Helm Dry Run
      run: |
        ls -la
        ls -la central-helm-chart
        ls -la main
        ls -la main/charts